name: Continuous Integration

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Clone, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          repository: ledgerhq/ledger-app-builder
          dockerfile: Dockerfile
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          tags: latest
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          repository: ledgerhq/ledger-app-builder/ledger-app-builder
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
