# Build the docker image and push it to GitHub Packages

name: Publish Docker images

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ${{ github.repository }}

jobs:
  builder_lite:
    name: App Builder Lite
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: ledger-app-builder-lite

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}

      - name: Set-up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set-up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push container
        uses: docker/build-push-action@v3
        with:
          file: lite/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
